spring.application.name=EstACE_V2

# URL de Conexion
spring.datasource.url=jdbc:postgresql://db.opxlxuiivszxzcmrdnyk.supabase.co:5432/postgres?sslmode=require

# Credenciales ocultas usando Variables de Entorno
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# SOLUCION AL ERROR DE RENDER (Prepared Statements)
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# Configuracion de Seguridad JWT
application.security.jwt.secret-key=${SECRET_KEY}
application.security.jwt.expiration=36000000

# --- CONFIGURACION DE CORREO (Spring Mail) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL de tu frontend (Para construir el enlace de recuperacion)
# Cuando se suba a produccion, cambiar esto por URL real de Vercel/Render
frontend.url=${FRONTEND_URL}